# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn compile

  deploy:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run: npm install vsce
      - run: node_modules/.bin/vsce publish minor -p ${VSCE_TOKEN}
      - run: git add package.json
      - run: git config user.email ${GIT_EMAIL}
      - run: git config user.name ${GIT_NAME}
      - run: git config push.default simple
      - run: "git commit -m ':rocket: Update version after deployment [ci skip]'"
      - run: git push --set-upstream origin ${CIRCLE_BRANCH}

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


